version: '3.8'

services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PUID=1000
      - PGID=1000
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=secret
    volumes:
      - /mnt/externaldrive/nextcloud/html:/config
      - /mnt/externaldrive/nextcloud/data:/data
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=secret
    volumes:
      - /mnt/externaldrive/postgres/data:/var/lib/postgresql/data
